[project]
name = "cf-to-openshift-agent"
version = "0.1.0"
dependencies = [
    "click>=8.2.1",
    "gitpython>=3.1.44",
    "jinja2>=3.1.6",
    "langchain>=0.3.26",
    "langchain-community>=0.3.26",
    "openai>=1.93.0",
]
